fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /account

madef_cms:
    resource: "@MadefCmsBundle/Resources/config/routing.yml"
    prefix:   /

madef_user:
    resource: "@MadefUserBundle/Resources/config/routing.yml"
    prefix:   /
