security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_PAGE_VIEW:    ROLE_ADMIN
        ROLE_PAGE_EDIT:    [ROLE_ADMIN, ROLE_PAGE_VIEW]
        ROLE_VERSION_VIEw: ROLE_ADMIN
        ROLE_VERSION_EDIT: [ROLE_ADMIN, ROLE_VERSION_VIEW]
        ROLE_WIDGET:       ROLE_ADMIN
        ROLE_LAYOUT:       ROLE_ADMIN
        ROLE_MEDIA:        ROLE_ADMIN
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_PAGE_VIEW, ROLE_PAGE_EDIT, ROLE_VERSION_VIEW, ROLE_VERSION_EDIT, ROLE_WIDGET, ROLE_LAYOUT, ROLE_MEDIA, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /account/login
                check_path: /account/login_check
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            anonymous:    true
            logout:
                path:       /account/logout
                target:     /

    access_control:
        - { path: ^/account/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/.*/page$, role: ROLE_PAGE_VIEW }
        - { path: ^/admin/.*/page, role: ROLE_PAGE_EDIT }
        - { path: ^/admin/.*/layout, role: ROLE_LAYOUT }
        - { path: ^/admin/.*/media, role: ROLE_MEDIA }
        - { path: ^/admin/.*/widget, role: ROLE_WIDGET }
        - { path: ^/admin/.*/version$, role: ROLE_VERSION_VIEW }
        - { path: ^/admin/.*/version, role: ROLE_VERSION_EDIT }
        - { path: ^/admin/.*/user, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
