parameters:
#    madef_cms.example.class: Madef\CmsBundle\Example

services:
    madef_cms.listener.menu:
        class: Madef\CmsBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_listener, event: menu.left, method: addToMenuLeft }
    madef_cms.listener.role:
        class: Madef\CmsBundle\Listener\RoleListener
        tags:
            - { name: kernel.event_listener, event: roles, method: addRoles }
